### ISSUE TITLE
Examples using mvc pattern ?

### ISSUE THREAD

**Issue by giannik** [hydrostack/hydro-todo#1]
The examples here use razor pages. Are there examples that use the standard mvc pattern (controller , action, razor view) ? 
Thank you

**Comment by kjeske** [comment]
In this project, the connection between Hydro and Razor Pages is in the [page view](https://github.com/hydrostack/hydro-todo/blob/main/Pages/Home/Index.cshtml), which has `<hydro name="..." /> `. In MVC it will be very similar, because you need to put `<hydro name="..." />` in the view returned by your controller.

**Comment by giannik** [comment]
so in my current mvc controller i have  a post method to change the state of an object method : 

```

 [HttpPost, ActionName(nameof(Edit))]
        public Task<IActionResult> EditPOST(string contentItemId, [Bind(Prefix = "submit.Save")] string submitSave, string returnUrl)
        {}

```


In hydro i would add this method   in the component code class (Save or Delete methods). 

 Correct ? 

So basically you do not handle http codes anywhere (like post or delete verbs).

**Comment by kjeske** [comment]
Yes, correct.

In Hydro component code behind you add:

```c#
public string ContentItemId { get; set; }

public Task Edit()
{
    await _yourService.Edit(ContentItemId);
}
```

In Hydro component view:

```razor
<button type="submit" hydro-on:click="@(() => Model.Edit())">Save</button>
```

The communication is transparent here, no manual HTTP calls. The HTTP call to your component is handled automatically by Hydro.
